#!/usr/bin/ruby

require 'fileutils'
require 'pathname'

unless File.basename(Dir.getwd) == "shared" and File.exists? "install"
  puts "You must run this from the `shared` directory. Example: `$ cd shared && ./install`"  
  exit
end

script = <<END
cd shared/
./update
END

hook = "../.git/modules/shared/hooks/post-receive"
FileUtils.mkpath File.dirname(hook)
FileUtils.rm hook, force: true 
IO.write hook, script

puts "------> Added post-receive hook."

system "./update"

puts "------> Updated symlinks."
